dist: trusty
sudo: false

install: true

language: java
jdk: oraclejdk8

before_script:
 - echo $JAVA_OPTS
 - export JAVA_OPTS='-Xms1g -Xmx3g'


env :
 - FLAGS="-greatspnpath $(pwd)/gspn"  TEST=$(ls oracle/*PT*SS.out)
 - FLAGS="-greatspnpath $(pwd)/gspn -order FR"  TEST=$(ls oracle/*PT*SS.out)
 

script :
 - ./install_greatspn.sh
 - ./install_eclipse.sh
 - (rc=0 ; for MODEL in $TEST ; do ./run_test.pl $MODEL.out $FLAGS || rc=$? ; done; exit $rc) 

