
install: true

addons: 
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['expat', 'libgmp-dev', 'gcc-5', 'libpopt-dev']

language: java

before_script:
 - echo $JAVA_OPTS
 - export JAVA_OPTS='-Xms1g -Xmx3g'

env :
 - FLAGS='-smt'
 - FLAGS='-its'
 - FLAGS="-ltsminpath $(pwd)/lts_install_dir"
 - FLAGS="-ltsminpath $(pwd)/lts_install_dir -smt" 
 - FLAGS="-ltsminpath $(pwd)/lts_install_dir -its" 
 - FLAGS="-its -smt" 
 - FLAGS="-ltsminpath $(pwd)/lts_install_dir -its -smt" 

script :
 - gcc --version 
 - ./run_all.sh $FLAGS

jdk: oraclejdk8

  
#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#  local_dir: fr.lip6.move.gal.updatesite/target/repository
#  on:
#    branch: master
