
install: true

addons: 
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['expat', 'libgmp-dev', 'gcc-5', 'libpopt-dev']

language: java

before_script:
 - echo $JAVA_OPTS
 - export JAVA_OPTS='-Xms1g -Xmx3g'

env :
 - FLAGS='-smt'
 - FLAGS='-its'
 - FLAGS="-ltsminpath $(pwd)/lts_install_dir"
 - FLAGS="-ltsminpath $(pwd)/lts_install_dir -disablePOR" 
 - FLAGS="-ltsminpath $(pwd)/lts_install_dir -smt" 
 - FLAGS="-ltsminpath $(pwd)/lts_install_dir -its" 
 - FLAGS="-its -smt" 
 - FLAGS="-ltsminpath $(pwd)/lts_install_dir -its -smt" 
 - FLAGS="-onlyGAL"
 - TEST="oracle/AirplaneLD-COL-0010-CTLC"
 - TEST="oracle/AirplaneLD-COL-0010-CTLC"
 - TEST="oracle/AirplaneLD-COL-0010-CTLF"
 - TEST="oracle/AirplaneLD-COL-0010-LTLC"
 - TEST="oracle/AirplaneLD-COL-0010-RC"
 - TEST="oracle/AirplaneLD-COL-0010-RD"
 - TEST="oracle/AirplaneLD-COL-0010-RF"
 - TEST="oracle/AirplaneLD-COL-0010-SS"
 - TEST="oracle/AirplaneLD-COL-0010-UB"
 - TEST="oracle/AirplaneLD-COL-1000-RD"
 - TEST="oracle/AirplaneLD-PT-0010-CTLC"
 - TEST="oracle/AirplaneLD-PT-0010-CTLF"
 - TEST="oracle/AirplaneLD-PT-0010-LTLC"
 - TEST="oracle/AirplaneLD-PT-0010-RC"
 - TEST="oracle/AirplaneLD-PT-0010-RD"
 - TEST="oracle/AirplaneLD-PT-0010-RF"
 - TEST="oracle/AirplaneLD-PT-0010-SS"
 - TEST="oracle/AirplaneLD-PT-0010-UB"
 - TEST="oracle/Angiogenesis-PT-01-CTLC"
 - TEST="oracle/Angiogenesis-PT-01-CTLF"
 - TEST="oracle/Angiogenesis-PT-01-LTLC"
 - TEST="oracle/Angiogenesis-PT-01-LTLF"
 - TEST="oracle/Angiogenesis-PT-01-RC"
 - TEST="oracle/Angiogenesis-PT-01-RD"
 - TEST="oracle/Angiogenesis-PT-01-RF"
 - TEST="oracle/Angiogenesis-PT-01-SS"
 - TEST="oracle/Angiogenesis-PT-01-UB"
 - TEST="oracle/AutoFlight-PT-01a-CTLC"
 - TEST="oracle/AutoFlight-PT-01a-CTLF"
 - TEST="oracle/AutoFlight-PT-01a-LTLC"
 - TEST="oracle/AutoFlight-PT-01a-LTLF"
 - TEST="oracle/AutoFlight-PT-01a-RC"
 - TEST="oracle/AutoFlight-PT-01a-RD"
 - TEST="oracle/AutoFlight-PT-01a-RF"
 - TEST="oracle/AutoFlight-PT-01a-SS"
 - TEST="oracle/AutoFlight-PT-01a-UB"
 - TEST="oracle/BridgeAndVehicles-COL-V04P05N02-CTLC"
 - TEST="oracle/BridgeAndVehicles-COL-V04P05N02-CTLF"
 - TEST="oracle/BridgeAndVehicles-COL-V04P05N02-LTLC"
 - TEST="oracle/BridgeAndVehicles-COL-V04P05N02-LTLF"
 - TEST="oracle/BridgeAndVehicles-COL-V04P05N02-RC"
 - TEST="oracle/BridgeAndVehicles-COL-V04P05N02-RD"
 - TEST="oracle/BridgeAndVehicles-COL-V04P05N02-RF"
 - TEST="oracle/BridgeAndVehicles-COL-V04P05N02-SS"
 - TEST="oracle/BridgeAndVehicles-COL-V04P05N02-UB"
 - TEST="oracle/CircadianClock-PT-000001-CTLC"
 - TEST="oracle/CircadianClock-PT-000001-CTLF"
 - TEST="oracle/CircadianClock-PT-000001-LTLC"
 - TEST="oracle/CircadianClock-PT-000001-LTLF"
 - TEST="oracle/CircadianClock-PT-000001-RC"
 - TEST="oracle/CircadianClock-PT-000001-RD"
 - TEST="oracle/CircadianClock-PT-000001-RF"
 - TEST="oracle/CircadianClock-PT-000001-SS"
 - TEST="oracle/CircadianClock-PT-000001-UB"
 - TEST="oracle/CircularTrains-PT-012-CTLC"
 - TEST="oracle/CircularTrains-PT-012-CTLF"
 - TEST="oracle/CircularTrains-PT-012-LTLC"
 - TEST="oracle/CircularTrains-PT-012-LTLF"
 - TEST="oracle/CircularTrains-PT-012-RC"
 - TEST="oracle/CircularTrains-PT-012-RD"
 - TEST="oracle/CircularTrains-PT-012-RF"
 - TEST="oracle/CircularTrains-PT-012-SS"
 - TEST="oracle/CircularTrains-PT-012-UB"
 - TEST="oracle/CSRepetitions-PT-02-CTLC"
 - TEST="oracle/CSRepetitions-PT-02-CTLF"
 - TEST="oracle/CSRepetitions-PT-02-LTLC"
 - TEST="oracle/CSRepetitions-PT-02-LTLF"
 - TEST="oracle/CSRepetitions-PT-02-RC"
 - TEST="oracle/CSRepetitions-PT-02-RD"
 - TEST="oracle/CSRepetitions-PT-02-RF"
 - TEST="oracle/CSRepetitions-PT-02-SS"
 - TEST="oracle/CSRepetitions-PT-02-UB"
 - TEST="oracle/DatabaseWithMutex-PT-02-CTLC"
 - TEST="oracle/DatabaseWithMutex-PT-02-CTLF"
 - TEST="oracle/DatabaseWithMutex-PT-02-LTLC"
 - TEST="oracle/DatabaseWithMutex-PT-02-LTLF"
 - TEST="oracle/DatabaseWithMutex-PT-02-RC"
 - TEST="oracle/DatabaseWithMutex-PT-02-RD"
 - TEST="oracle/DatabaseWithMutex-PT-02-RF"
 - TEST="oracle/DatabaseWithMutex-PT-02-SS"
 - TEST="oracle/DatabaseWithMutex-PT-02-UB"
 - TEST="oracle/Dekker-PT-010-CTLC"
 - TEST="oracle/Dekker-PT-010-CTLF"
 - TEST="oracle/Dekker-PT-010-LTLC"
 - TEST="oracle/Dekker-PT-010-LTLF"
 - TEST="oracle/Dekker-PT-010-RC"
 - TEST="oracle/Dekker-PT-010-RD"
 - TEST="oracle/Dekker-PT-010-RF"
 - TEST="oracle/Dekker-PT-010-SS"
 - TEST="oracle/Dekker-PT-010-UB"
 - TEST="oracle/DES-PT-00a-RC"
 - TEST="oracle/DES-PT-00a-RD"
 - TEST="oracle/DES-PT-00a-RF"
 - TEST="oracle/DES-PT-00a-SS"
 - TEST="oracle/DES-PT-00a-UB"
 - TEST="oracle/Diffusion2D-PT-D05N010-CTLC"
 - TEST="oracle/Diffusion2D-PT-D05N010-CTLF"
 - TEST="oracle/Diffusion2D-PT-D05N010-LTLC"
 - TEST="oracle/Diffusion2D-PT-D05N010-LTLF"
 - TEST="oracle/Diffusion2D-PT-D05N010-RC"
 - TEST="oracle/Diffusion2D-PT-D05N010-RD"
 - TEST="oracle/Diffusion2D-PT-D05N010-RF"
 - TEST="oracle/Diffusion2D-PT-D05N010-SS"
 - TEST="oracle/Diffusion2D-PT-D05N010-UB"
 - TEST="oracle/DLCshifumi-PT-2a-CTLC"
 - TEST="oracle/DLCshifumi-PT-2a-CTLF"
 - TEST="oracle/DLCshifumi-PT-2a-LTLC"
 - TEST="oracle/DLCshifumi-PT-2a-LTLF"
 - TEST="oracle/DLCshifumi-PT-2a-RC"
 - TEST="oracle/DLCshifumi-PT-2a-RD"
 - TEST="oracle/DLCshifumi-PT-2a-RF"
 - TEST="oracle/DLCshifumi-PT-2a-SS"
 - TEST="oracle/DLCshifumi-PT-2a-UB"
 - TEST="oracle/DrinkVendingMachine-COL-02-CTLC"
 - TEST="oracle/DrinkVendingMachine-COL-02-CTLF"
 - TEST="oracle/DrinkVendingMachine-COL-02-LTLC"
 - TEST="oracle/DrinkVendingMachine-COL-02-LTLF"
 - TEST="oracle/DrinkVendingMachine-COL-02-RC"
 - TEST="oracle/DrinkVendingMachine-COL-02-RD"
 - TEST="oracle/DrinkVendingMachine-COL-02-RF"
 - TEST="oracle/DrinkVendingMachine-COL-02-SS"
 - TEST="oracle/DrinkVendingMachine-COL-02-UB"
 - TEST="oracle/Eratosthenes-PT-010-CTLC"
 - TEST="oracle/Eratosthenes-PT-010-CTLF"
 - TEST="oracle/Eratosthenes-PT-010-LTLC"
 - TEST="oracle/Eratosthenes-PT-010-LTLF"
 - TEST="oracle/Eratosthenes-PT-010-RC"
 - TEST="oracle/Eratosthenes-PT-010-RD"
 - TEST="oracle/Eratosthenes-PT-010-RF"
 - TEST="oracle/Eratosthenes-PT-010-SS"
 - TEST="oracle/Eratosthenes-PT-010-UB"
 - TEST="oracle/Eratosthenes-PT-200-LTLC"
 - TEST="oracle/Eratosthenes-PT-200-LTLF"
 - TEST="oracle/Eratosthenes-PT-200-SS"
 - TEST="oracle/Eratosthenes-PT-500-LTLC"
 - TEST="oracle/Eratosthenes-PT-500-LTLF"
 - TEST="oracle/Eratosthenes-PT-500-SS"
 - TEST="oracle/FMS-PT-002-CTLC"
 - TEST="oracle/FMS-PT-002-CTLF"
 - TEST="oracle/FMS-PT-002-LTLC"
 - TEST="oracle/FMS-PT-002-LTLF"
 - TEST="oracle/FMS-PT-002-RC"
 - TEST="oracle/FMS-PT-002-RD"
 - TEST="oracle/FMS-PT-002-RF"
 - TEST="oracle/FMS-PT-002-SS"
 - TEST="oracle/FMS-PT-002-UB"
 - TEST="oracle/IBM319-PT-none-CTLC"
 - TEST="oracle/IBM319-PT-none-CTLF"
 - TEST="oracle/IBM319-PT-none-LTLC"
 - TEST="oracle/IBM319-PT-none-LTLF"
 - TEST="oracle/IBM319-PT-none-RC"
 - TEST="oracle/IBM319-PT-none-RD"
 - TEST="oracle/IBM319-PT-none-RF"
 - TEST="oracle/IBM319-PT-none-SS"
 - TEST="oracle/IBM319-PT-none-UB"
 - TEST="oracle/Kanban-PT-0005-CTLC"
 - TEST="oracle/Kanban-PT-0005-CTLF"
 - TEST="oracle/Kanban-PT-0005-LTLC"
 - TEST="oracle/Kanban-PT-0005-LTLF"
 - TEST="oracle/Kanban-PT-0005-RC"
 - TEST="oracle/Kanban-PT-0005-RD"
 - TEST="oracle/Kanban-PT-0005-RF"
 - TEST="oracle/Kanban-PT-0005-SS"
 - TEST="oracle/Kanban-PT-0005-UB"
 - TEST="oracle/MAPK-PT-008-CTLC"
 - TEST="oracle/MAPK-PT-008-CTLF"
 - TEST="oracle/MAPK-PT-008-LTLC"
 - TEST="oracle/MAPK-PT-008-LTLF"
 - TEST="oracle/MAPK-PT-008-RC"
 - TEST="oracle/MAPK-PT-008-RD"
 - TEST="oracle/MAPK-PT-008-RF"
 - TEST="oracle/MAPK-PT-008-SS"
 - TEST="oracle/MAPK-PT-008-UB"
 - TEST="oracle/Peterson-COL-2-CTLC"
 - TEST="oracle/Peterson-COL-2-CTLF"
 - TEST="oracle/Peterson-COL-2-LTLC"
 - TEST="oracle/Peterson-COL-2-LTLF"
 - TEST="oracle/Peterson-COL-2-RC"
 - TEST="oracle/Peterson-COL-2-RD"
 - TEST="oracle/Peterson-COL-2-RF"
 - TEST="oracle/Peterson-COL-2-SS"
 - TEST="oracle/Peterson-COL-2-UB"
 - TEST="oracle/Peterson-PT-2-CTLC"
 - TEST="oracle/Peterson-PT-2-CTLF"
 - TEST="oracle/Peterson-PT-2-LTLC"
 - TEST="oracle/Peterson-PT-2-LTLF"
 - TEST="oracle/Peterson-PT-2-RC"
 - TEST="oracle/Peterson-PT-2-RD"
 - TEST="oracle/Peterson-PT-2-RF"
 - TEST="oracle/Peterson-PT-2-SS"
 - TEST="oracle/Peterson-PT-2-UB"
 - TEST="oracle/Philosophers-COL-000005-CTLC"
 - TEST="oracle/Philosophers-COL-000005-CTLF"
 - TEST="oracle/Philosophers-COL-000005-LTLC"
 - TEST="oracle/Philosophers-COL-000005-LTLF"
 - TEST="oracle/Philosophers-COL-000005-RC"
 - TEST="oracle/Philosophers-COL-000005-RD"
 - TEST="oracle/Philosophers-COL-000005-RF"
 - TEST="oracle/Philosophers-COL-000005-SS"
 - TEST="oracle/Philosophers-COL-000005-UB"
 - TEST="oracle/Raft-PT-02-CTLC"
 - TEST="oracle/Raft-PT-02-CTLF"
 - TEST="oracle/Raft-PT-02-LTLC"
 - TEST="oracle/Raft-PT-02-LTLF"
 - TEST="oracle/Raft-PT-02-RC"
 - TEST="oracle/Raft-PT-02-RD"
 - TEST="oracle/Raft-PT-02-RF"
 - TEST="oracle/Raft-PT-02-SS"
 - TEST="oracle/Raft-PT-02-UB"
 - TEST="oracle/Railroad-PT-005-CTLC"
 - TEST="oracle/Railroad-PT-005-CTLF"
 - TEST="oracle/Railroad-PT-005-LTLC"
 - TEST="oracle/Railroad-PT-005-LTLF"
 - TEST="oracle/Railroad-PT-005-RC"
 - TEST="oracle/Railroad-PT-005-RD"
 - TEST="oracle/Railroad-PT-005-RF"
 - TEST="oracle/Railroad-PT-005-SS"
 - TEST="oracle/Railroad-PT-005-UB"
 - TEST="oracle/SafeBus-COL-03-CTLC"
 - TEST="oracle/SafeBus-COL-03-CTLF"
 - TEST="oracle/SafeBus-COL-03-LTLC"
 - TEST="oracle/SafeBus-COL-03-LTLF"
 - TEST="oracle/SafeBus-COL-03-RC"
 - TEST="oracle/SafeBus-COL-03-RD"
 - TEST="oracle/SafeBus-COL-03-RF"
 - TEST="oracle/SafeBus-COL-03-SS"
 - TEST="oracle/SafeBus-COL-03-UB"
 - TEST="oracle/SwimmingPool-PT-01-CTLC"
 - TEST="oracle/SwimmingPool-PT-01-CTLF"
 - TEST="oracle/SwimmingPool-PT-01-LTLC"
 - TEST="oracle/SwimmingPool-PT-01-LTLF"
 - TEST="oracle/SwimmingPool-PT-01-RC"
 - TEST="oracle/SwimmingPool-PT-01-RD"
 - TEST="oracle/SwimmingPool-PT-01-RF"
 - TEST="oracle/SwimmingPool-PT-01-SS"
 - TEST="oracle/SwimmingPool-PT-01-UB"
 - TEST="oracle/TokenRing-COL-005-CTLC"
 - TEST="oracle/TokenRing-COL-005-CTLF"
 - TEST="oracle/TokenRing-COL-005-LTLC"
 - TEST="oracle/TokenRing-COL-005-LTLF"
 - TEST="oracle/TokenRing-COL-005-RC"
 - TEST="oracle/TokenRing-COL-005-RD"
 - TEST="oracle/TokenRing-COL-005-RF"
 - TEST="oracle/TokenRing-COL-005-SS"
 - TEST="oracle/TokenRing-COL-005-UB"
 - TEST="oracle/TokenRing-PT-005-CTLC"
 - TEST="oracle/TokenRing-PT-005-CTLF"
 - TEST="oracle/TokenRing-PT-005-LTLC"
 - TEST="oracle/TokenRing-PT-005-LTLF"
 - TEST="oracle/TokenRing-PT-005-RC"
 - TEST="oracle/TokenRing-PT-005-RD"
 - TEST="oracle/TokenRing-PT-005-RF"
 - TEST="oracle/TokenRing-PT-005-SS"
 - TEST="oracle/TokenRing-PT-005-UB"

script :
 - ./tag.sh $FLAGS
 - ./install_all.sh
 - ./run_test.pl $TEST.out $FLAGS 2> logs/$TEST.err | tee logs/$TEST.out | grep test
 - tar czf logs.tgz logs/
 - mv logs.tgz website/

jdk: oraclejdk8

cache:
  directories:
    - eclipse/
    - INPUTS/
    
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: website/
  on:
    branch: master
